// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTEGcM5jugxgaYtmJ3IgamR_ensPxivE4',
    appId: '1:322576596423:web:f525ccd334a0c4e32aade2',
    messagingSenderId: '322576596423',
    projectId: 'phoneauth-6c9c7',
    authDomain: 'phoneauth-6c9c7.firebaseapp.com',
    storageBucket: 'phoneauth-6c9c7.appspot.com',
    measurementId: 'G-LJJ9DKGGKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmK35fLmSJQSPgUAfSWVsIkdKZnKdYttk',
    appId: '1:322576596423:android:fc0b94c3501f64742aade2',
    messagingSenderId: '322576596423',
    projectId: 'phoneauth-6c9c7',
    storageBucket: 'phoneauth-6c9c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtQ0uOBZEPhGGZNu38bcur55Tkrg8hO2I',
    appId: '1:322576596423:ios:fba29bc7bbf3b6a82aade2',
    messagingSenderId: '322576596423',
    projectId: 'phoneauth-6c9c7',
    storageBucket: 'phoneauth-6c9c7.appspot.com',
    androidClientId: '322576596423-7nb5vrvhjlsvh3r5hv168m0r0c04o2lo.apps.googleusercontent.com',
    iosClientId: '322576596423-fpcgmsl66vjdiomqarke1jp5lsj4sik3.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2',
  );
}
